"""
Flask Web Dashboard for Coop Camera
Provides 10 different UI variants for viewing camera streams, stats, and recorded videos
"""
from flask import Flask, render_template, Response, jsonify, send_from_directory
import requests
import os
import re
from datetime import datetime

app = Flask(__name__,
            static_folder='dist',
            static_url_path='')

# Configuration
COOPCAM_BASE_URL = os.getenv('COOPCAM_URL', 'http://localhost:5001')
CAMERA_RESOLUTION = {'width': 1280, 'height': 720}

def get_vite_assets():
    """Parse index.html to get the actual asset filenames generated by Vite"""
    index_path = os.path.join(app.static_folder, 'index.html')

    if not os.path.exists(app.static_folder):
        print(f"ERROR: dist folder not found at {app.static_folder}")
        print("Please run: npm run build")
        return {'js': '/assets/index.js', 'css': '/assets/index.css', 'error': True}

    if os.path.exists(index_path):
        with open(index_path, 'r') as f:
            content = f.read()
            # Extract JS file (matches both index-*.js and main-*.js patterns)
            js_match = re.search(r'src="(/assets/[^"]+\.js)"', content)
            # Extract CSS file (matches both index-*.css and main-*.css patterns)
            css_match = re.search(r'href="(/assets/[^"]+\.css)"', content)

            assets = {
                'js': js_match.group(1) if js_match else '/assets/index.js',
                'css': css_match.group(1) if css_match else '/assets/index.css'
            }
            print(f"Loaded assets: {assets}")
            return assets

    print(f"ERROR: index.html not found at {index_path}")
    print("Please run: npm run build")
    return {'js': '/assets/index.js', 'css': '/assets/index.css', 'error': True}

@app.route('/')
def index():
    """Main dashboard page"""
    assets = get_vite_assets()
    return render_template('index.html', assets=assets)

# API endpoints for data
@app.route('/api/stats')
def get_stats():
    """Get camera and system statistics"""
    stats = {
        'camera': {
            'status': 'online',
            'fps': 30,
            'resolution': f"{CAMERA_RESOLUTION['width']}x{CAMERA_RESOLUTION['height']}",
            'uptime': '24h 15m'
        },
        'detections': {
            'today': 127,
            'this_week': 856,
            'this_month': 3420
        },
        'system': {
            'cpu': 45,
            'memory': 62,
            'storage': 78,
            'temperature': 42
        },
        'models': {
            'active': 'model4',
            'available': ['model1', 'model2', 'model3', 'model4', 'nodetect']
        }
    }
    return jsonify(stats)

@app.route('/api/videos')
def get_videos():
    """Get list of recorded videos"""
    # Mock data - in production this would scan a recordings directory
    videos = [
        {
            'id': 1,
            'filename': 'recording_2025-01-08_14-30.mp4',
            'timestamp': '2025-01-08 14:30:45',
            'duration': '00:05:23',
            'size': '45.2 MB',
            'thumbnail': '/api/thumbnail/1'
        },
        {
            'id': 2,
            'filename': 'recording_2025-01-08_09-15.mp4',
            'timestamp': '2025-01-08 09:15:12',
            'duration': '00:03:47',
            'size': '32.8 MB',
            'thumbnail': '/api/thumbnail/2'
        },
        {
            'id': 3,
            'filename': 'recording_2025-01-07_18-45.mp4',
            'timestamp': '2025-01-07 18:45:33',
            'duration': '00:07:15',
            'size': '61.5 MB',
            'thumbnail': '/api/thumbnail/3'
        },
        {
            'id': 4,
            'filename': 'recording_2025-01-07_12-20.mp4',
            'timestamp': '2025-01-07 12:20:08',
            'duration': '00:04:52',
            'size': '41.3 MB',
            'thumbnail': '/api/thumbnail/4'
        },
        {
            'id': 5,
            'filename': 'recording_2025-01-06_16-05.mp4',
            'timestamp': '2025-01-06 16:05:22',
            'duration': '00:06:38',
            'size': '56.7 MB',
            'thumbnail': '/api/thumbnail/5'
        }
    ]
    return jsonify(videos)

@app.route('/api/stream/<model>')
def stream_video(model):
    """Proxy video stream from coopcam.py"""
    stream_url = f"{COOPCAM_BASE_URL}/stream/{model}"

    def generate():
        try:
            r = requests.get(stream_url, stream=True, timeout=10)
            r.raise_for_status()
            for chunk in r.iter_content(chunk_size=1024):
                if chunk:
                    yield chunk
        except requests.exceptions.ConnectionError:
            print(f"❌ Cannot connect to coopcam.py at {COOPCAM_BASE_URL}")
            print(f"   Please start coopcam.py on port 5001")
            # Return empty response - frontend will show error state
            return
        except Exception as e:
            print(f"Stream error for {model}: {e}")
            return

    return Response(generate(),
                   mimetype='multipart/x-mixed-replace; boundary=frame')

@app.route('/api/thumbnail/<video_id>')
def get_thumbnail(video_id):
    """Get video thumbnail (mock endpoint)"""
    # In production, this would return actual video thumbnails
    return jsonify({'placeholder': True, 'video_id': video_id})

# Serve React app
@app.route('/<path:path>')
def serve_static(path):
    """Serve static files from React build"""
    return send_from_directory(app.static_folder, path)

if __name__ == '__main__':
    print("\n" + "="*60)
    print("🐔 Coop Camera Dashboard")
    print("="*60)
    print(f"📡 Dashboard: http://localhost:5000")
    print(f"🎥 Looking for coopcam.py at: {COOPCAM_BASE_URL}")
    print("\n⚠️  Make sure coopcam.py is running on port 5001!")
    print("   If not, the camera stream will show 'Stream unavailable'")
    print("="*60 + "\n")

    app.run(debug=True, host='0.0.0.0', port=5000)
